apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: nodejs-pod
 labels:
  author: saikiran
  type: nodejs
spec:
 scaleTargetRef:
  apiVersion: apps/v1
  kind: Deployment
  name: nodejs-pod
 minReplicas: 3
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50
